name: Build EXE on Release

on:
  release:
    types: [published]  # Nur wenn ein Release veröffentlicht wird

jobs:
  build-windows-exe:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onefile main.py
        # Ergebnis liegt in dist/main.exe

      - name: Upload EXE to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/main.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
