name: Build and Upload .exe on Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build .exe with pyinstaller
        run: |
          pyinstaller --onefile main.py --name wsjt_log_analyzer
        # This will create a dist/main.exe file

      - name: Upload .exe to release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/wsjt_log_analyzer.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
